Python Bindings Recorded.formatPath() bails if airdate is not  set.
Calling 'Recorded.formatPath("%U/%T/%pY-%pm-%pd %pH.%pi %T")' on a valid
Recorded instance, gives a traceback.

Recorded.formatPath  without valid airdate:

Traceback (most recent call last):
  File "test/test_Dataheap_Recorded_001.py", line 116, in test_Dataheap_Recorded_001_04
    print(rec.formatPath("%U/%T/%pY-%pm-%pd %pH.%pi %T"))
  File "MythTV/dataheap.py", line 440, in formatPath
    path = path.replace('%o'+tag, airdate.strftime(format))
ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900

Setting 'airdate' to
_default_datetime = datetime(1900,1,1, tzinfo=datetime.UTCTZ())
cures it.

(cherry picked from commit d2d3cb8f76ac4f9072f4a5a53de9046c95044ca2)