MythTV python: Class System.system: correct typo.
When calling System.system, the following traceback bails:

Traceback
  File "MythTV/system.py", line 56, in system
    command = command.lsplit(' ',1)
AttributeError: 'str' object has no attribute 'lsplit'

Note the typo: 'lsplit' --> 'split'.
Python has [lr]strip methods, but provides only 'split()' and 'rsplit()'.

(cherry picked from commit 75c2982a1e4a8a6631eeae542fceb89d11fe5588)